-- 제1회 쀼 피클볼 대항전
-- 주의: 이 파일을 다시 실행하면 기존 경기 결과가 초기화됩니다.

DROP TABLE IF EXISTS public.matches;
DROP TABLE IF EXISTS public.players;

CREATE TABLE public.players (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  gender text NOT NULL CHECK (gender IN ('M', 'F')),
  team_id integer NOT NULL CHECK (team_id BETWEEN 1 AND 4),
  display_order integer NOT NULL
);

CREATE TABLE public.matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('doubles', 'mens', 'womens')),
  round integer NOT NULL CHECK (round BETWEEN 1 AND 3),
  match_no integer NOT NULL UNIQUE,
  side_a bigint[] NOT NULL,
  side_b bigint[] NOT NULL,
  set1_a integer, set1_b integer,
  set2_a integer, set2_b integer,
  set3_a integer, set3_b integer,
  status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed')),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competitor_size_check CHECK (
    (category = 'doubles' AND cardinality(side_a) = 2 AND cardinality(side_b) = 2)
    OR
    (category IN ('mens', 'womens') AND cardinality(side_a) = 1 AND cardinality(side_b) = 1)
  ),
  CONSTRAINT score_range_check CHECK (
    (set1_a IS NULL OR set1_a BETWEEN 0 AND 99) AND
    (set1_b IS NULL OR set1_b BETWEEN 0 AND 99) AND
    (set2_a IS NULL OR set2_a BETWEEN 0 AND 99) AND
    (set2_b IS NULL OR set2_b BETWEEN 0 AND 99) AND
    (set3_a IS NULL OR set3_a BETWEEN 0 AND 99) AND
    (set3_b IS NULL OR set3_b BETWEEN 0 AND 99)
  )
);

ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- 브라우저가 Supabase를 직접 읽거나 수정하지 않고 Next.js 서버 API만 사용합니다.
REVOKE ALL ON TABLE public.players FROM anon, authenticated;
REVOKE ALL ON TABLE public.matches FROM anon, authenticated;

-- 참가자
-- 팀1 곽성민-성지혜 / 팀2 김정훈-조혜민 / 팀3 윤희철-이지영 / 팀4 박성민-심우연
INSERT INTO public.players (name, gender, team_id, display_order) VALUES
('곽성민', 'M', 1, 1),
('김정훈', 'M', 2, 2),
('윤희철', 'M', 3, 3),
('박성민', 'M', 4, 4),
('성지혜', 'F', 1, 5),
('조혜민', 'F', 2, 6),
('이지영', 'F', 3, 7),
('심우연', 'F', 4, 8);

-- 4팀/4명 풀리그 표준 3라운드 편성
-- R1: 1-4, 2-3 / R2: 1-3, 4-2 / R3: 1-2, 3-4

-- 부부 복식 6경기
INSERT INTO public.matches (category, round, match_no, side_a, side_b) VALUES
('doubles', 1, 1, ARRAY[1,5]::bigint[], ARRAY[4,8]::bigint[]),
('doubles', 1, 2, ARRAY[2,6]::bigint[], ARRAY[3,7]::bigint[]),
('doubles', 2, 3, ARRAY[1,5]::bigint[], ARRAY[3,7]::bigint[]),
('doubles', 2, 4, ARRAY[4,8]::bigint[], ARRAY[2,6]::bigint[]),
('doubles', 3, 5, ARRAY[1,5]::bigint[], ARRAY[2,6]::bigint[]),
('doubles', 3, 6, ARRAY[3,7]::bigint[], ARRAY[4,8]::bigint[]);

-- 남자 단식 6경기
INSERT INTO public.matches (category, round, match_no, side_a, side_b) VALUES
('mens', 1, 7, ARRAY[1]::bigint[], ARRAY[4]::bigint[]),
('mens', 1, 8, ARRAY[2]::bigint[], ARRAY[3]::bigint[]),
('mens', 2, 9, ARRAY[1]::bigint[], ARRAY[3]::bigint[]),
('mens', 2, 10, ARRAY[4]::bigint[], ARRAY[2]::bigint[]),
('mens', 3, 11, ARRAY[1]::bigint[], ARRAY[2]::bigint[]),
('mens', 3, 12, ARRAY[3]::bigint[], ARRAY[4]::bigint[]);

-- 여자 단식 6경기
INSERT INTO public.matches (category, round, match_no, side_a, side_b) VALUES
('womens', 1, 13, ARRAY[5]::bigint[], ARRAY[8]::bigint[]),
('womens', 1, 14, ARRAY[6]::bigint[], ARRAY[7]::bigint[]),
('womens', 2, 15, ARRAY[5]::bigint[], ARRAY[7]::bigint[]),
('womens', 2, 16, ARRAY[8]::bigint[], ARRAY[6]::bigint[]),
('womens', 3, 17, ARRAY[5]::bigint[], ARRAY[6]::bigint[]),
('womens', 3, 18, ARRAY[7]::bigint[], ARRAY[8]::bigint[]);
